name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  uses: 
    run-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      
      -name: npm install, test and build
       run:|
        npm install
        npm run build
        
      
   
